# Generated by Django 3.2.9 on 2022-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='subject',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
