# Generated by Django 3.2.9 on 2022-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_auto_20220111_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished_courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='language.Courses'),
        ),
    ]
