# Generated by Django 3.2.9 on 2022-01-12 17:30

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0010_alter_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='1'),
            preserve_default=False,
        ),
    ]
